[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 开启电脑监视器的高速打印
monitor_speed = 115200

; (可选) 如果你的电脑有多个串口冲突，可以在这里取消注释并强制指定
; monitor_port = COM4
; upload_port = COM4